export const CATEGORIES_ACTION_TYPES = {
    SET_CATEGORIES: 'category/SET_CATEGORIES_MAP',
    FECTH_CATEGORIES_START: 'category/FECTH_CATEGORIES_START',
    FECTH_CATEGORIES_SUCCESS: 'category/FECTH_CATEGORIES_SUCCESS',
    FECTH_CATEGORIES_FAILED: 'category/FECTH_CATEGORIES_FAILED',
}